# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='checkin.proto',
  package='checkin',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rcheckin.proto\x12\x07\x63heckin\"\xaf\x01\n\x0e\x43heckinRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nandroid_id\x18\x02 \x01(\x03\x12,\n\x05\x62uild\x18\x03 \x01(\x0b\x32\x1d.checkin.CheckinRequest.Build\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\x05\x1a.\n\x05\x42uild\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\x12\x10\n\x08hardware\x18\x02 \x01(\t\"=\n\x0f\x43heckinResponse\x12\x12\n\nandroid_id\x18\x01 \x01(\x03\x12\x16\n\x0esecurity_token\x18\x02 \x01(\x03')
)




_CHECKINREQUEST_BUILD = _descriptor.Descriptor(
  name='Build',
  full_name='checkin.CheckinRequest.Build',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='checkin.CheckinRequest.Build.fingerprint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware', full_name='checkin.CheckinRequest.Build.hardware', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=202,
)

_CHECKINREQUEST = _descriptor.Descriptor(
  name='CheckinRequest',
  full_name='checkin.CheckinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='checkin.CheckinRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='android_id', full_name='checkin.CheckinRequest.android_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build', full_name='checkin.CheckinRequest.build', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='checkin.CheckinRequest.locale', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='checkin.CheckinRequest.version', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHECKINREQUEST_BUILD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=202,
)


_CHECKINRESPONSE = _descriptor.Descriptor(
  name='CheckinResponse',
  full_name='checkin.CheckinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='android_id', full_name='checkin.CheckinResponse.android_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_token', full_name='checkin.CheckinResponse.security_token', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=265,
)

_CHECKINREQUEST_BUILD.containing_type = _CHECKINREQUEST
_CHECKINREQUEST.fields_by_name['build'].message_type = _CHECKINREQUEST_BUILD
DESCRIPTOR.message_types_by_name['CheckinRequest'] = _CHECKINREQUEST
DESCRIPTOR.message_types_by_name['CheckinResponse'] = _CHECKINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckinRequest = _reflection.GeneratedProtocolMessageType('CheckinRequest', (_message.Message,), dict(

  Build = _reflection.GeneratedProtocolMessageType('Build', (_message.Message,), dict(
    DESCRIPTOR = _CHECKINREQUEST_BUILD,
    __module__ = 'checkin_pb2'
    # @@protoc_insertion_point(class_scope:checkin.CheckinRequest.Build)
    ))
  ,
  DESCRIPTOR = _CHECKINREQUEST,
  __module__ = 'checkin_pb2'
  # @@protoc_insertion_point(class_scope:checkin.CheckinRequest)
  ))
_sym_db.RegisterMessage(CheckinRequest)
_sym_db.RegisterMessage(CheckinRequest.Build)

CheckinResponse = _reflection.GeneratedProtocolMessageType('CheckinResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHECKINRESPONSE,
  __module__ = 'checkin_pb2'
  # @@protoc_insertion_point(class_scope:checkin.CheckinResponse)
  ))
_sym_db.RegisterMessage(CheckinResponse)


# @@protoc_insertion_point(module_scope)
