name: Extract Instagram APK from Aptoide

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  extract_download_link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip list | grep requests  # Debugging ke liye

      - name: Debug - Show Installed Python Packages
        run: pip list

      - name: Create and Run Extraction Script
        run: |
          echo 'import requests
import re

def get_aptoide_download_link(package_name):
    url = f"https://en.aptoide.com/app/{package_name}"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Error: Unable to access {url}")
        exit(1)
    match = re.search(r'"apkUrl":"(https://[^"]+)"', response.text)
    if match:
        print(f"Direct Download Link: {match.group(1)}")
    else:
        print("Error: Download link not found.")
        exit(1)

package_name = "com.instagram.android"
get_aptoide_download_link(package_name)' > script.py
          python script.py
