name: Extract Instagram APK from Aptoide

on:
  push:
    branches:
      - main  # Yahan apni branch ka naam change kar sakte ho
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract_download_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Repo ko checkout karne ke liye

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run extraction script
        run: |
          echo "import requests
import re

def get_aptoide_download_link(package_name):
    url = f'https://en.aptoide.com/app/{package_name}'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f'Error: Unable to access {url}')
        return None
    match = re.search(r'\"apkUrl\":\"(https://[^\"]+)\"', response.text)
    if match:
        return match.group(1)
    print('Error: Download link not found.')
    return None

package_name = 'com.instagram.android'
download_link = get_aptoide_download_link(package_name)

if download_link:
    print(f'Direct Download Link: {download_link}')
else:
    exit(1)" > script.py
          python script.py
