name: Extract Instagram APK from Aptoide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  extract_download_link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip freeze | grep requests  # Yeh check karega ki requests install hua ya nahi

      - name: Debug - Show Installed Python Packages
        run: pip list  # Yeh debug step dikhayega ki kaunse packages install hue hain

      - name: Run extraction script
        run: |
          cat <<EOF > script.py
import requests
import re

def get_aptoide_download_link(package_name):
    url = f'https://en.aptoide.com/app/{package_name}'
    headers =
